# Generated by Django 4.2.10 on 2025-03-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='recipes.recipe'),
        ),
    ]
